[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[start]
cmd = "cd backend && gunicorn flask_app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 2"
